name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      # Linting
      - name: Check code style
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm test

      - name: build
        run: npm run build
